title: "༩ ༢ ༡ ༤"
baseurl:

# config
date_format: "%y:%j"
permalink:   :title
exclude:     ["drafts/"]

markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM

# contact info
author:
    email:
      icon: envelope
      link: mailto:9214@protonmail.com
    telegram:
      icon: telegram
      link: https://t.me/lllllllllillilillll
    github:
      icon: github-alt 
      link: https://github.com/9214
    instagram:
      icon: instagram 
      link: https://www.instagram.com/lllllllllillilillll/
    last-fm:
      icon: lastfm-square
      link: https://www.last.fm/user/ghsthrdwr
    goodreads:
      icon: book
      link: https://goodreads.com/9214
    steam:
      icon: steam
      link: http://steamcommunity.com/id/lllllllllillilillll

# third-party services
google_analytics:
disqus_shortname:
