title: "༩ ༢ ༡ ༤"
baseurl:

# config
date_format: "%y:%j"
permalink:   :title
exclude:     ["drafts/"]

markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  style: compressed

# contact info
author:
    email:
      fret: s
      icon: envelope
      link: mailto:9214@protonmail.com
    telegram:
      fret: b
      icon: telegram
      link: https://t.me/lllllllllillilillll
    github:
      fret: b
      icon: github-alt 
      link: https://github.com/9214
    instagram:
      fret: b
      icon: instagram 
      link: https://www.instagram.com/lllllllllillilillll/
    tips:
      fret: b
      icon: ethereum
      link: https://etherscan.io/address/0x6a15006e3370ba4f390960073cc0823a2b04663d

# third-party services
google_analytics:
disqus_shortname:
